#!/bin/env bash

rm -rf users

set -eu

grep -v -E "^requests[[:space:]]|^rich[[:space:]]|\[tool.poetry.dependencies\]|^python[[:space:]]" pyproject.toml > temppyproject.toml

echo -e '\n[tool.poetry.dependencies]\npython = "^3.7"' >> temppyproject.toml

pip list | grep -E "^requests[[:space:]]|^rich[[:space:]]" | \
    sed -e 's/  /=/' -e 's/ //g' -e 's/=/ = \"\^/' -e 's/$/\"/' >> temppyproject.toml


sed -i '/^[[:space:]]*$/d' temppyproject.toml
tail -n 4 temppyproject.toml

mv temppyproject.toml pyproject.toml


if [ $# -gt 0 ]; then
    echo "$2"
    git add .
    git status
    git commit -m "$2 $(date)"

    echo
    git push -u origin master
fi